<?php
/**
 * @file
 * Install, update, and uninstall functions for the PSFAUtils module.
 */

/**
 * Upgrade from Drupal 7.
 */
function psfautils_update_1000() {
  // Convert D7 variables to config.
  $config = config('psfautils.settings');
  $config->set('opinion_of_backdrop', update_variable_get('psfautils_opinion_drupal', 'Awesome!'));
  $config->save();

  // Delete D7 variables.
  update_variable_del('psfautils_opinion_drupal');
}
